services:
  postgres:
    build: .
    container_name: postgres
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Jakarta}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - homelab
    ports:
      - "${BIND_IP}:${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "${POSTGRES_CPU_LIMIT:-1}"
          memory: ${POSTGRES_MEMORY_LIMIT:-1G}

networks:
  homelab:
    external: true

volumes:
  postgres_data:
