services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Jakarta}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_USER: ${MARIADB_USER:-root}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - homelab
    ports:
      - "${BIND_IP}:${MARIADB_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "${MARIADB_CPU_LIMIT:-1}"
          memory: ${MARIADB_MEMORY_LIMIT:-1G}

networks:
  homelab:
    external: true

volumes:
  mariadb_data:
